name: Publish JupyterLab Extension

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"
          cache: npm
          cache-dependency-path: packages/jupyterlab/package-lock.json
      - name: Install dependencies
        working-directory: packages/jupyterlab
        run: npm install
      - name: Build
        run: npm run build:jupyterlab
      - name: Publish
        working-directory: packages/jupyterlab
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
